import { ArrowRight, LogOut, MapPin, Package, UserRound } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";

export default function Account() {
  const { user, isAuthenticated, loading, logout } = useAuth();
  if (loading) return <div className="account-page"><div className="loading-pulse" /><div className="loading-pulse short" /><div className="loading-card" /></div>;
  if (!isAuthenticated) return <div className="account-page"><div className="account-login-card"><div className="account-icon"><UserRound size={22} /></div><p className="section-kicker">Área pessoal</p><h1 className="page-title mt-3">As suas escolhas,<br /><em>num só lugar.</em></h1><p className="mx-auto mt-5 max-w-sm text-[15px] leading-7 text-[#536178]">Inicie sessão para consultar encomendas, guardar favoritos e manter o seu perfil Mercato.</p><Button className="mt-8 rounded-full bg-[#155eef] px-7 py-6" onClick={startLogin}>Iniciar sessão <ArrowRight size={17} /></Button><p className="mt-4 text-xs text-[#7b8799]">Ligação segura via Manus OAuth.</p></div></div>;
  return <div className="mx-auto max-w-[1100px] px-5 pb-24 pt-12 lg:pt-20"><div className="flex flex-col justify-between gap-6 border-b border-[#10203a]/10 pb-10 sm:flex-row sm:items-end"><div><p className="section-kicker">A minha conta</p><h1 className="page-title mt-3">Olá, <em>{user?.name?.split(" ")[0] ?? "por aqui"}.</em></h1><p className="mt-3 text-[15px] text-[#536178]">Tudo o que precisa, guardado e simples.</p></div><button className="text-link self-start sm:self-auto" onClick={() => void logout()}>Terminar sessão <LogOut size={15} /></button></div><div className="account-grid"><div className="account-card"><div className="account-card-icon"><Package size={20} /></div><p className="section-kicker">Encomendas</p><h2>Histórico de compras</h2><p>As suas encomendas vão aparecer aqui assim que a primeira descoberta chegar.</p><span className="account-card-link">Ver encomendas <ArrowRight size={15} /></span></div><div className="account-card"><div className="account-card-icon"><MapPin size={20} /></div><p className="section-kicker">Moradas</p><h2>Entrega sem esforço</h2><p>Guarde as suas moradas favoritas para tornar o próximo checkout mais rápido.</p><span className="account-card-link">Gerir moradas <ArrowRight size={15} /></span></div><div className="account-card account-card-wide"><div><p className="section-kicker">O seu perfil</p><h2>{user?.name ?? "Cliente Mercato"}</h2><p>{user?.email ?? "Email não disponível"}</p></div><div className="profile-avatar">{(user?.name ?? "M").slice(0, 1).toUpperCase()}</div></div></div><div className="account-footnote"><span>Precisa de ajuda?</span><Link href="/shop" className="text-link">Fale connosco <ArrowRight size={15} /></Link></div></div>;
}
