import { ArrowRight, ArrowUpRight, Check, Clock3, Leaf, ShieldCheck, Sparkles, Truck } from "lucide-react";
import { Link } from "wouter";
import { ProductCard } from "@/components/ProductCard";
import { categoryMeta, featuredProducts, formatPrice } from "@/data/catalog";
import { useCart } from "@/hooks/useCart";
import { Button } from "@/components/ui/button";

export default function Home() {
  const cart = useCart();
  return <div>
    <section className="hero-section mx-auto max-w-[1440px] px-5 pb-16 pt-8 lg:px-10 lg:pb-24 lg:pt-12">
      <div className="hero-grid">
        <div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Curadoria de outubro <ArrowUpRight size={14} /></div><h1 className="hero-title">Encontre<br /><em>o que fica.</em></h1><p className="hero-subtitle">Objetos com intenção, marcas com história e pequenas descobertas para todos os dias.</p><div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/shop"><Button className="rounded-full bg-[#155eef] px-6 py-6 text-[15px] hover:bg-[#0e4ac7]">Explorar a curadoria <ArrowRight size={17} /></Button></Link><Link href="/shop?category=Casa" className="text-link">Ver mais vendidos <ArrowUpRight size={15} /></Link></div><div className="hero-note"><span className="avatar-stack"><span>AM</span><span>FC</span><span>LR</span></span><span><strong>+2.400 pessoas</strong> encontraram um favorito esta semana.</span></div></div>
        <div className="hero-visual"><img src="/manus-storage/async-images/OSM00crb9FU0rI5qfsVz6H/image-1.webp" alt="Cadeira azul e objetos de design num estúdio de luz quente" /><div className="hero-float-card"><span className="float-card-label">Peça em foco</span><strong>Arc Lounge Chair</strong><span className="flex items-center gap-1 text-xs text-[#536178]">Casa <span className="text-[#b3bdc9]">·</span> {formatPrice(449)}</span><Link href="/product/arc-lounge-chair" className="float-card-link">Ver peça <ArrowUpRight size={14} /></Link></div><span className="hero-stamp">M/26<br /><small>EDIT</small></span></div>
      </div>
      <div className="trust-row"><div><Truck size={18} /><span><strong>Entrega gratuita</strong><small>Em compras acima de 120€</small></span></div><div><ShieldCheck size={18} /><span><strong>Escolhas seguras</strong><small>Pagamento protegido</small></span></div><div><Leaf size={18} /><span><strong>Curadoria consciente</strong><small>Menos, mas melhor</small></span></div><div><Clock3 size={18} /><span><strong>Trocas simples</strong><small>30 dias para decidir</small></span></div></div>
    </section>
    <section className="mx-auto max-w-[1440px] px-5 py-10 lg:px-10 lg:py-16"><div className="section-heading"><div><p className="section-kicker">Escolha o seu ritmo</p><h2 className="section-title">Comece por aqui.</h2></div><Link href="/shop" className="text-link">Ver todas <ArrowUpRight size={15} /></Link></div><div className="category-grid">{categoryMeta.map(category => <Link key={category.label} href={`/shop?category=${category.label}`} className="category-card group"><div className={`category-art bg-gradient-to-br ${category.tone}`}><span className="category-symbol">{category.label === "Casa" ? "⌂" : category.label === "Tech" ? "↗" : category.label === "Estilo" ? "✳" : "≈"}</span><span className="category-arrow"><ArrowUpRight size={20} /></span></div><div className="mt-4 flex items-end justify-between"><div><h3 className="font-display text-[21px] font-bold tracking-[-0.04em]">{category.label}</h3><p className="mt-1 text-sm text-[#7b8799]">{category.note}</p></div><span className="text-xs font-bold uppercase tracking-[0.12em] text-[#155eef]">Explorar</span></div></Link>)}</div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-12 lg:px-10 lg:py-20"><div className="section-heading"><div><p className="section-kicker">A seleção que pede atenção</p><h2 className="section-title">Em destaque.</h2></div><Link href="/shop" className="text-link">Ver catálogo completo <ArrowUpRight size={15} /></Link></div><div className="product-grid">{featuredProducts.map(product => <ProductCard product={product} key={product.id} />)}</div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-10 lg:px-10 lg:py-16"><div className="editorial-panel"><div><p className="section-kicker text-[#d7f64a]">A ideia por trás</p><h2 className="editorial-title">Comprar menos.<br /><span>Escolher melhor.</span></h2><p className="mt-6 max-w-md text-[15px] leading-7 text-[#c5cfdf]">O Mercato junta marcas independentes e objetos que sobrevivem à tendência. Uma seleção pequena, editada com cuidado, para uma vida com mais espaço.</p><Link href="/shop" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-white underline decoration-[#d7f64a] decoration-2 underline-offset-8">Conheça a curadoria <ArrowRight size={16} /></Link></div><div className="editorial-list"><div><span>01</span><p><strong>Descobrir</strong><small>Uma seleção fora do ruído.</small></p></div><div><span>02</span><p><strong>Escolher</strong><small>Detalhes que fazem diferença.</small></p></div><div><span>03</span><p><strong>Ficar</strong><small>Peças para usar e repetir.</small></p></div></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 pb-20 pt-10 text-center lg:px-10"><div className="newsletter-panel"><Sparkles className="mx-auto mb-4 text-[#155eef]" size={22} /><p className="section-kicker">O melhor chega primeiro</p><h2 className="mt-2 font-display text-3xl font-bold tracking-[-0.05em] md:text-4xl">Uma nota de bom gosto.</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#536178]">Novos objetos, pequenas histórias e escolhas com intenção — uma vez por semana.</p><form className="mx-auto mt-6 flex max-w-md gap-2" onSubmit={event => event.preventDefault()}><input className="newsletter-input" type="email" placeholder="O seu email" /><Button className="rounded-full bg-[#155eef] px-5">Subscrever</Button></form><div className="mt-4 flex items-center justify-center gap-2 text-xs text-[#7b8799]"><Check size={13} className="text-[#155eef]" /> Sem spam. Só coisas boas.</div></div></section>
  </div>;
}
